# fly.toml app configuration file generated for asics-store on 2024-01-15T10:30:00Z

app = "asics-store"
primary_region = "dfw"

[build]

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512